name: Android CI

on:
  workflow_dispatch:
    branches: [main]
  push:
    branches: [main]
    paths:
      - "app/src/**"
  pull_request:
    branches: [main]
    paths:
      - "app/src/**"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FIREBASE_SECRET: ${{ secrets.FIREBASE_SECRET }}
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: set up secrets
        run: echo $FIREBASE_SECRET > app/google-services.json
      - name: Set up Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Run firebase emulator
        run: |
          npm install -g firebase-tools
          firebase emulators:exec -c ./firestore/firebase.json &
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Lint Project
        run: ./gradlew lint
      - name: Test with Gradle
        run: ./gradlew testStagingDebugUnitTest
      - name: run UI tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck
